development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hiex_dev
  pool: 5
  username: root
  password: rootroot
  socket: /var/run/mysqld/mysqld.sock

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hiex_staging
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
